= STATEMENT OF WORK: 1

THIS *MASTER SERVICES AGREEMENT* (this *_“Agreement”_*) is between Party One, (*_“Party One”_*), and Party Two (*_“Contractor”*_*).

This Statement of Work (*_“SOW”_*) is entered into by and Party One (*_“Party One”_*) and Party Two (*_“Contractor”_*).  This SOW is entered into pursuant to the Master Services Agreement between Party One and Contractor (*_“Agreement”_*).  This SOW is subject to the terms and conditions contained in the Agreement and is made a part thereof. Any term not otherwise defined herein shall have the meaning specified in the Agreement. In the event of any conflict or inconsistency between the terms of this SOW and the terms of the Agreement, the terms of this SOW shall govern and prevail. 

. *Period of Performance.* This SOW will commence on the effective date of the Agreement and continue until the Services have been completed or otherwise terminated pursuant to the Agreement or as otherwise set forth herein (*_“Term”_*). 

. *Services & Deliverables.* Contractor shall provide the following services and deliverables (collectively, the *_“Services”_*):

. *Project Change Control Procedure.* The following process will be followed if a change to this SOW is required: 

.. A Project Change Request (*_“PCR”_*) will be the vehicle for communicating change.  The PCR must describe the change, the rationale for the change, and the effect the change will have on the project.

.. The designated project manager of the requesting party (Contractor or Party One) will review the proposed change and determine whether to submit the request to the other party. 

.. Both project managers will review the proposed change and approve it for further investigation or reject it.  Party One and Contractor will mutually agree upon the fees associated with such investigation, if any.  If the investigation is authorized, Party One’s project manager will sign the PCR, which will constitute approval for any investigation fees.  The investigation will determine the effect that the implementation of the PCR will have on the Fees associated with this SOW, as well as, schedule and any other terms and conditions. 

.. Upon completion of the investigation, both parties will review the impact of the proposed change and, if mutually agreed, a Change Authorization will be executed.  

.. A written Change Authorization and/or PCR must be signed by both parties to authorize implementation of the investigated changes.  

. Fees

